name: Docker Image CI

on:
  push:
    branches:
      - multilib

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [alpine, centos7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build centos7 image
        if: matrix.variant == 'centos7'
        run: |
          docker buildx build --progress=plain \
            --platform linux/amd64 --load --rm \
            -t you54f/holy-build-box:4.0.0-amd64-${{ matrix.variant }} \
            -f Dockerfile-amd64-centos7 --pull \
            --build-arg OPENSSL_1_1_LEGACY=false \
            --build-arg DISABLE_OPTIMIZATIONS=0 .
      - name: Build alpine image
        if: matrix.variant == 'alpine'
        run: |
          docker buildx build --progress=plain \
            --platform linux/amd64 --load --rm \
            -t you54f/holy-build-box:4.0.0-amd64-${{ matrix.variant }} \
            -f Dockerfile-alpine --pull \
            --build-arg OPENSSL_1_1_LEGACY=false \
            --build-arg DISABLE_OPTIMIZATIONS=0 .


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: matrix.variant == 'centos7' || matrix.variant == 'alpine'
        run: |
          docker push you54f/holy-build-box:4.0.0-amd64-${{ matrix.variant }}
  
  build-and-publish-arm:
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        variant: [alpine, centos7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build centos7 image
        if: matrix.variant == 'centos7'
        run: |
          docker buildx build --progress=plain \
            --platform linux/arm64 --load --rm \
            -t you54f/holy-build-box:4.0.0-arm64-${{ matrix.variant }} \
            -f Dockerfile-arm64-centos7 --pull \
            --build-arg OPENSSL_1_1_LEGACY=false \
            --build-arg DISABLE_OPTIMIZATIONS=0 .
      - name: Build alpine image
        if: matrix.variant == 'alpine'
        run: |
          docker buildx build --progress=plain \
            --platform linux/arm64 --load --rm \
            -t you54f/holy-build-box:4.0.0-arm64-${{ matrix.variant }} \
            -f Dockerfile-alpine --pull \
            --build-arg OPENSSL_1_1_LEGACY=false \
            --build-arg DISABLE_OPTIMIZATIONS=0 .


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: matrix.variant == 'centos7' || matrix.variant == 'alpine'
        run: |
          docker push you54f/holy-build-box:4.0.0-arm64-${{ matrix.variant }}

